### ISSUE TITLE
Specs for input/output formats

### ISSUE THREAD

**Issue by lgarron** [Voltara/vcube#1]
I'm trying to define puzzle interchange formats at https://standards.cubing.net/

I'd love it if you documented your formats and helped standards.cubing.net have matching specs!

Also, I've been leaning towards calling the positional format Reid notation, given that Reid's solver is the oldest use of it that I've found. Any chance you have a reference to Singmaster using it?

**Comment by Voltara** [comment]
I had the same question myself regarding how to name the positional notation.  Even as early as "Notes on Rubik's Magic Cube" (1979), Singmaster uses a clockwise (URF) notation for corners, whereas Reid's solver uses counterclockwise (UFR).  The format is attributed to Singmaster in Tomas Rokicki's solver (https://github.com/rokicki/cube20src/blob/7fe13ca4aa55bef8a8b0d95de58de7c0bd8568c7/cubepos.w#L1292), so I named it that way for consistency.  I would certainly support renaming it to reflect more accurately the origin of the notation.  Perhaps @rokicki could lend some insight?

Regarding the other formats, the only novel one I use is the Speffz cycle notation.  When I was testing the solver, I needed a quick and concise way to inspect a cube and manually input its position (the Reid notation was a bit too cumbersome.)  Because I had recently learned the M2/OP blindfolded method, Speffz with A/U (i.e. ULB/DF) buffers was a convenient choice.  I allow configuring the buffer pieces as a command-line option; to use it as an interchange format would require standardizing on specific buffers.  In that case, A/A (i.e. ULB/UB) would feel less arbitrary than my defaults.

When I get a chance I'll write up a more formal description of the Speffz format.  Thanks for your feedback.
