### ISSUE TITLE
Solving questions

### ISSUE THREAD

**Issue by wanfuse123** [Voltara/vcube#2]
How can I skip corners edges and centers for the larger cube?

Is there a way to optimize it for this configuration?

I assume it would be faster?

**Comment by Voltara** [comment]
There's no built-in option for ignoring edges or corners, but it can be adapted easily into an edges-only or corners-only solver (I'm not sure about centers though.)

1. **Redefine the `U` move to permute either only corners, or only edges:**

https://github.com/Voltara/vcube/blob/290f5ccf520ec75196f5351e0fb109a1d4fcf74e/src/cube.h#L427-L430

The above line of code defines what a `U` move does.  The first array element is the corner permutation, and the second+third elements are the edge permutation.

```cpp
// Corners-only:
static constexpr cube M_U    = {0x0706050402010003,0x0b0a0908,0x0706050403020100};

// Edges-only:
static constexpr cube M_U    = {0x0706050403020100,0x0b0a0908,0x0706050402010003};
```

2. **Regenerate src/const-cubes.h then rebuild vc-optimal**

Note: Changing `M_U` will cause unit tests to fail.

```sh
make gen-const-cubes
./gen-const-cubes > src/const-cubes.h
make vc-optimal
```

3. **Regenerate pruning tables**

Any pruning tables that were saved to `tables/nxprune_*` will no longer be valid.  Either move them out of the `tables/` directory, or delete them.  If you loaded pruning tables into shared memory, you will also need to remove those as well (`ipcs -m | grep 0x7663` to list them, then `ipcrm -M 0x7663####` to remove each.)

After deleting the old tables, they will regenerate next time you run `vc-optimal`.  I would recommend trying the smaller variants (`--coord=304` `--coord=112` or `--coord=208`) first.  The default 21GiB table is probably overkill for corners-only and edges-only solving.

4. **Be careful how you input cubes**

The default input format (sequence of moves) will work without modification, because it uses the same definition of `M_U` as the solver.  As it reads your input, the moves it applies will leave either the edges or corners alone.

However, if you use the `reid` or `speffz` input formats, you need to make sure your input is a cube with solved edges (or corners) -- otherwise the cube will be unsolvable.

Alternatively, you can modify `src/vc-optimal.cpp` to call `c.setEdgePerm(0)` or `c.setCornerPerm(0)` after it reads each cube.  (Setting the permutation automatically resets the orientation.)

**Comment by wanfuse123** [comment]
What if I just feed it configurations where corners and edges are already
in the right places? Will this strategy be affective?

**Comment by Voltara** [comment]
If you mean inputting those configurations without modifying the software, then no, that won't work for two reasons:

1. Because it's still trying to solve the entire cube, such a configuration might not even be solvable due to parity.  (Odd corner permutation + solved edges, for example.)

2. The edges-only or corners-only solutions wouldn't be optimal.  As an illustration, consider the superflip position where all corners are solved, and all edges are flipped in-place.  That position requires a minimum of 20 moves to solve (`U  R2 F  B  R  B2 R  U2 L  B2 R  U' D' R2 F  R' L  B2 U2 F2`).  But if all you care about are the edges, you can flip all edges in-place in as few as 14 moves (`U  R  U  D' F' U' D  B  R  D  F  R  L  F`)

One thing I should mention is the pruning tables in this solver are not well-suited for solving only edges or corners.  The reason is that they still include information about both corners and edges regardless of whether or not you're using it -- so they end up being inefficient for their size.  To solve the 14-move edges-only superflip above on my laptop took 19 seconds using the 2.4GiB table, and 41 seconds using the 7.3GiB table.  (Although it's a larger table, it contains less information about edge flip, that's evidently important for that particular position.)
