### ISSUE TITLE
Maintaining a running count maximum depth

### ISSUE THREAD

**Issue by ArhanChaudhary** [Voltara/vcube#3]
Would it be possible to modify vcube to efficiently find the shortest algorithm solution in a list of scrambles? This would imply a running maximum for the --depth parameter. ie When a new shortest length algorithm is found from the input, the solver now only checks for solutions until that depth. Could vcube be modified to do this dynamically?

**Comment by Voltara** [comment]
You can modify it relatively easily to work as you describe.  The search depth (`cf.depth`) is passed into the solver on this line of code: https://github.com/Voltara/vcube/blob/9f5bc2cce18f29437879ace825f22917f6705378/src/vc-optimal.cpp#L394

Then after this call to `moves.canonical()`, you can check the solution length (`moves.size()`) to see if it's a new minimum.  Just be aware that if no solution is found, the solver will return an empty move sequence which you'll want to ignore unless the input cube was already solved to begin with (`c == cube{}`):
https://github.com/Voltara/vcube/blob/9f5bc2cce18f29437879ace825f22917f6705378/src/vc-optimal.cpp#L397

Access to `cf.depth` will also need to be made thread-safe.

Depending on how many cubes you're dealing with, you might find it faster to run the entire input through the solver with a small depth limit (maybe 13-15 depending on pruning table size) and work your way up incrementally until you find a solution.  Since this involves running the solver several times, you'll want to use the `--shm` option to avoid having to reload the pruning table every startup.

**Comment by ArhanChaudhary** [comment]
Thanks for the info, I'll fork the repo soon and follow what you described. My input size is hundreds of thousands of cubes, so I think the latter modification of cf.depth would be better for my use case. I've never used C++ before, so just to confirm it would look like this

```cpp
...
auto moves = S.solve(c, best_depth);
std::chrono::duration<double> elapsed = std::chrono::steady_clock::now() - t0;
moves = moves.canonical();
mtx.lock();
// my use case guarantees that every input has a solution so i can skip the empty move sequence check
if (moves.size() < best_depth) {
    best_depth = moves.size();
}
mtx.unlock();
...
```

**Comment by Voltara** [comment]
That looks roughly correct.  A couple comments:

Depending on if you're looking for _all_ of the shortest solutions, or just one, you'll want to pass either `best_depth` or `best_depth - 1` into `S.solve()`.

The line where `S.solve()` is called is still reading `best_depth` without a mutex.  It would be safest to copy `best_depth` to a local variable while the mutex is still locked.

You still need to check for an empty "not found" return from the solver, because although your input cubes are all solvable, the search depth limit will prevent many of those solutions from being found.

**Comment by ArhanChaudhary** [comment]
TYSM for the impromptu code review, does this look better?
```cpp
uint64_t solution_id = next_id++;
if (cf.ordered) {
    solutionp = solutions.insert(solutions.end(), "");
}
int synced_best_depth = best_depth;
mtx.unlock();
...
auto moves = S.solve(c, synced_best_depth - 1);
std::chrono::duration<double> elapsed = std::chrono::steady_clock::now() - t0;
moves = moves.canonical();
if (moves.size() != 0) {
    mtx.lock();
    if (moves.size() < best_depth) {
        best_depth = moves.size();
    }
    mtx.unlock();
}
...
```
