### ISSUE TITLE
Finding multiple canonical optimal solutions

### ISSUE THREAD

**Issue by ArhanChaudhary** [Voltara/vcube#4]
How could vcube be modified to find multiple optimal solutions that are unique by symmetry? My first instinct is to run the solver to the depth of the shortest optimal solution, but I do not know if these solutions will be unique nor how to implement the logic.

**Comment by Voltara** [comment]
The way it's currently written, it would take some effort to make the solver return all optimal solutions instead of just one.

The [solver::solve()](https://github.com/Voltara/vcube/blob/9f5bc2cce18f29437879ace825f22917f6705378/src/nxsolve.h#L75), [solver::search()](https://github.com/Voltara/vcube/blob/9f5bc2cce18f29437879ace825f22917f6705378/src/nxsolve.h#L104), and [solver::queue_search()](https://github.com/Voltara/vcube/blob/9f5bc2cce18f29437879ace825f22917f6705378/src/nxsolve.h#L104) functions are all designed to return immediately when the first solution is found, and reconstruct the move sequence as it works its way back up the call stack.

The [nxopt](https://github.com/rokicki/cube20src/) solver already implements returning all solutions (the `-A` option), so that would be the easiest way to get that.

As for the uniqueness of the solutions, vcube does some canonicalization of the move sequences, but it doesn't take into account cube symmetry.  It ensures that pairs of moves that commute (R, L for example) are output in a predictable order.  But the canonicalized forms of `U2D2R2L2F2B2` and `R2L2F2B2U2D2` would be different, even though they both solve the same position, and one move sequence is just a 120-degree rotation of the other.

To eliminate those duplicates whenever you're dealing with a symmetric position, you could transform the solution sequence according to each of the symmetries, then choose the lexicographically smallest one.

**Comment by ArhanChaudhary** [comment]
I think my best bet is to use the nxopt solver for multiple solutions and use this one for speed. From the source code, I don't understand how either of those functions work. Thanks for the info.
